/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: fongoose (https://sketchfab.com/fongoose)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/models/0641cc113cfb4a6ba7269aa696ae1512
title: RPG Reptile Mage
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-211.56, -190.06, -180.86]}>
          <mesh material={materials['08___Default']} geometry={nodes.mesh_0.geometry} />
          <mesh material={materials['02___Default']} geometry={nodes.mesh_1.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
